### ISSUE TITLE
Some improvements in requirements

### ISSUE THREAD

**Issue by jbrucker** [kaesrel/ku-polls#1]
Some of your requirements go beyond what's in the Vision Statement.
For now, avoid inventing your own requirements. No. 3, 4, and 7 are examples.
No. 5 is more general than the vision, and kind of vague.
No. 6 also vague. What restrictions? What did the vision say?

A requirement should be testable.  If its not specific, like "with certain restrictions"
then its difficult to test.

Later, in class, we may have a discussion about how to improve
the app and update the Vision accordingly. Offer your ideas then.

**Comment by kaesrel** [comment]
I have tried to fix the issue according to your comments.
I am still not quite sure if it is properly fixed, so I decide not to close the issue yet.
