### ISSUE TITLE
Some more specifics needed, one requirement doesn't match vision

### ISSUE THREAD

**Issue by jbrucker** [kaesrel/ku-polls#3]
Some requirements aren't clear whether they refer to all poll questions
or each one individually.  I posted on Google Classroom about this (it
comes up in lots of students' requirements).

In your requirements:
```
Poll creator user can set duration for voting and result viewing.
```
What's a "duration"?  It's not the same thing as starting date and closing date,
which is what we want.  (be specific)

The Vision says that a poll question and its results can be viewed
after the closing date, so the above requirement is not accurate.

**Comment by kaesrel** [comment]
Thank you sir.
The duration means the closing date for voting and opening date for result viewing. I clarified it.
